### ISSUE TITLE
Implement Sign Up and Sign In Functionality

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#1]
EPIC: User Authentication

As a **Site User**  I can **register an account and log in with existing user details** so that **I can have a personalized and secure experience**

### Acceptance Criteria:

- The user must be able to register with a username, password and password confirmation.
- The user must be able to log in with a username and password.
- Incorrect login attempts shall inform the user of an incorrect password or username.

### Tasks

- [x] Design and implement database models for users (Back-End).
- [x] Create API endpoints for registration and login (Back-End).
- [x] Design and implement registration and login forms (Front-End).
- [x] Connect the forms to API endpoints via Axios (Front-End).
- [x] Implement frontend validations for form fields (Front-End).
