### ISSUE TITLE
Implement Functionality to Create Groups

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#12]
EPIC: Group Management Feature

As a **user** I can **create, view, edit, and delete groups** so that **I can efficiently manage groups associated with tasks.**

### Acceptance Criteria:

- Users can create a new group by selecting an associated task, specifying a group size, and providing a description.
- Users can view details of a group, including the associated task, group size, and description.
- Users can edit and delete existing groups.

### Tasks

- [x] Implement the backend model, serializers, views, and URLs for groups.
- [x] Implement the frontend components and styles for creating, viewing, editing, and deleting groups.
- [x] Update navigation and home page to include links to the groups feature.
