### ISSUE TITLE
Implement Functionality to Create Tasks

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#2]
EPIC: Task management

As a **logged in user** I can **create new tasks within the application** so that **I can organize and plan my work more easily**

### Acceptance Criteria:

- The user should be presented with a form to fill in the details of the task.
- The user should be able to save the task, which results in it being added to the overall task list.
- After the task has been saved, the user should receive a visual confirmation.
- Error handling must be available if information is missing or incorrectly filled in.

### Tasks

- [x] Create models and database tables to manage task information (Back-End).
- [x] Implement API endpoints to create and save a task (Back-End).
- [x] Design and implement a user interface for creating new tasks, including forms and required components.
- [x] Connect forms with backend API to send and receive data.
