### ISSUE TITLE
Implement CRUD functionality for Tasks

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#3]
EPIC: Task management

As a **logged in user** I can **view details, edit and delete tasks** so that **I can effectively manage my daily activities**

### Acceptance Criteria:

- Users should be able to see a list of all their tasks.
- Users should be able to edit data by using a similar form as when creating.
- Users must be able to delete a task from the system.

### Tasks

- [x] Implement API endpoints to retrieve a list of tasks, a specific task, update a task, and delete a task (Back-End).
- [x] Ensure all necessary security measures and validations are in place to protect data integrity (Back-End).
- [x] Create and implement editing forms for tasks.
- [x] Implement a confirmation dialog before deleting data.
