### ISSUE TITLE
Implement Due Date, Priority, Category and Status Management for Tasks

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#4]
EPIC: Task management

As a **logged in user** I can **set due dates, set priority, category and status** so that **I can better organize and prioritize my tasks effectively**

### Acceptance Criteria:

- The user can set and change the due date, priority, category and status of a task.
- The system should offer a calendar component to select dates.
- Priorities may change at any time to reflect changing circumstances.
- The user can create new categories as needed.
- The status can be updated at any time to reflect the progress of the task.

### Tasks

- [x] Implement model changes to support storage of due date, priority, category and status (Back-End).
- [x] Update the API to handle CRUD operations for these new attributes (Back-End).
- [ ] Update the UI to include input fields and choices for these attributes in the task form (Front-End).
