### ISSUE TITLE
Enables Assignment and Deassignment of Task Owners

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#7]
EPIC: Task management

As a **task owner** I can **assign and unassign other users as owners of the task** so that **I can coordinate and delegate responsibilities effectively within my team**

### Acceptance Criteria:

- The user must be able to assign other users to a task by using a search function where usernames can be searched.
- The user who created the task has permission to add or remove users as the task owner.
- The user interface must clearly show which users are assigned as owners of the task.
- Only the user who created the task or has been assigned as owner should be able to see and edit the task.

### Tasks

- [x] Implement logic to handle assignment and deassignment of task owners, including authorization checks (Back-End).
- [x] Develop a search functionality to find users based on username (Back-End).
- [ ] Design and implement a user-friendly task owner assignment component, including a search function.
- [ ] Update UI to reflect changes in task owners and allow easy navigation and management.
