### ISSUE TITLE
Integrate Calendar Function to Sync with Tasks

### ISSUE THREAD

**Issue by merin86** [merin86/planbrella#9]
EPIC: Task management

As a **logged in user** I can **view a calendar in a dedicated section of the web page that automatically updates when new tasks are added** so that **I can see the due dates of my tasks in a visual and easy-to-understand way**

### Acceptance Criteria:

- The calendar must be clearly visible on a dedicated part of the website.
- The calendar should show current dates, weeks and months and enable navigation forward and backward in time.
- When new tasks are created with a due date, this date should automatically appear in the calendar.

### Tasks

- [ ] Develop and maintain API endpoints that support date-based data retrieval and updating (Back-End).
- [ ] Implement logic to manage synchronization between task changes and calendar updates (Back-End).
- [ ] Integrate a calendar component in the dedicated part of the web page (Front-End).
